---
title: "zooplancton part2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
SciViews:: R
```
```{r}
zooplankton_sub <- filter(zooplankton, class %in% c("Poecilostomatoid", "Calanoid", "Cyclopoid", "Harpacticoid"))
```

##ecd en fonction de l'aire
```{r}
chart(zooplankton_sub, formula = ecd ~ area %col=% perimeter) +
  geom_point(na.rm= TRUE) 
```


```{r}
library(ggridges)
```


##périmètre selon les classes
```{r}
chart(zooplankton_sub, class ~ perimeter %fill=% class %alpha=% class) +
  geom_density_ridges() 
```


##axe mineur de l'ellipsoïde en fonction de la classe
```{r}
chart(zooplankton_sub, formula = min ~ class %fill=% class) + 
  geom_violin() + 
  coord_flip()
```


##
```{r}
chart(zooplankton_sub, ~ elongation %alpha=% class) + 
  geom_histogram(bins=30) 
```


##
```{r}
chart(zooplankton_sub,formula=~ elongation %col=% class)+ 
  geom_density()
```


##
```{r}
chart(zooplankton_sub, formula= compactness ~ transparency %alpha=% class) + 
  geom_point(na.rm = TRUE)
```


##
```{r}
chart(zooplankton_sub, formula = ~ circularity) + 
  geom_density()
```


##
```{r}
chart(zooplankton_sub, formula = ~ transparency) + 
  geom_density()
```


##
```{r}
chart(zooplankton_sub, formula=~mean %col=% class %alpha=% class) + 
  geom_histogram()
```


##
```{r}
chart(zooplankton_sub, formula= elongation ~ circularity %col=% class %alpha=% class) + 
  geom_point()
```

